# This is a basic workflow to help you get started with Actions

name: DevCard

# Set permissions 
permissions:
  contents: write
  
on:
  # The workflow_dispatch tells the action it can manually run from the Actions tab.
  workflow_dispatch:
  push:
    branches:
      - main
    schedule:
      - cron: "0 0 * * *"

# create a new job that will run the DevCard GitHub action
jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.1.0
        with: 
          devcard_id: ${{ secrets.DEVCARD_ID2 }}
          
